__all__ = ['Ngram',
           'Interval',
           'Time',
           'Cumul',
           'HeadTail',
           'PktSec',
           'Burst',
           'TransPosition',
           'PktLen',
           'PktDistribution',
           'PktNum']
